export const categoryOptions = [
  { value: "sports", content: "Sports" },
  { value: "geography", content: "Geography" },
  { value: "music", content: "Music" },
  { value: "movies", content: "Movies" },
  { value: "fun", content: "Just for Fun" },
  { value: "miscellanous", content: "Miscellanous" },
  { value: "history", content: "History" },
  { value: "literature", content: "Literature" },
  { value: "language", content: "Language" },
  { value: "science", content: "Science" },
  { value: "gaming", content: "Gaming" },
  { value: "entertainment", content: "Entertainment" },
  { value: "religion", content: "Religion" },
  { value: "holiday", content: "Holiday" },
];