name: Unit Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "client/**"
      - "server/**"

  push:
    branches:
      - main
    paths:
      - "client/**"
      - "server/**"

jobs:
  client-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for Client
        uses: actions/setup-node@v3
        with:
          node-version: "22.15.0"
      - name: Install Client Dependencies
        working-directory: ./client
        run: npm install

      - name: Run Client Jest Tests
        working-directory: ./client
        run: npm test --skip-coverage

  server-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for Server
        uses: actions/setup-node@v3
        with:
          node-version: "22.15.0"

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm install

      - name: Run Server Jest Tests
        working-directory: ./server
        run: npm test
