name: Conditional Version Bump

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      server_changed: ${{ steps.filter.outputs.server }}
      client_changed: ${{ steps.filter.outputs.client }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            server:
              - 'server/**'
            client:
              - 'client/**'

  bump-server-version:
    needs: detect-changes
    if: needs.detect-changes.outputs.server_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js for server
        uses: actions/setup-node@v3
        with:
          node-version: "22.15.0"

      - name: Configure git user and remote with PAT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jon-zawada/Makedle.git

      - name: Bump server patch version
        working-directory: ./server
        run: |
          npm install
          npm version patch -m "chore(server): bump patch version to %s"
          git push origin main --follow-tags

  bump-client-version:
    needs: detect-changes
    if: needs.detect-changes.outputs.client_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js for client
        uses: actions/setup-node@v3
        with:
          node-version: "22.15.0"

      - name: Configure git user and remote with PAT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jon-zawada/Makedle.git

      - name: Bump client patch version
        working-directory: ./client
        run: |
          npm install
          npm version patch -m "chore(client): bump patch version to %s"
          git push origin main --follow-tags
